using System;
using BaiTapCoban;
using static BaiTapCoban.Bai1;
using static BaiTapCoban.Bai2;
using static BaiTapCoban.Bai3;
using static BaiTapCoban.Bai4;
using static BaiTapCoban.Bai5;
using static BaiTapCoban.Bai6;
using static BaiTapCoban.Bai7;
using static BaiTapCoban.Bai8;
using static BaiTapCoban.Bai9;
using static BaiTapCoban.Bai10;
using static BaiTapCoban.Bai11;
using static BaiTapCoban.Bai12;
using static BaiTapCoban.Bai13;
using static BaiTapCoban.Bai14;
using static BaiTapCoban.Bai15;
using static BaiTapCoban.Bai16;
using static BaiTapCoban.Bai17;
using static BaiTapCoban.Bai18;
using static BaiTapCoban.Bai19;
using static BaiTapCoban.Bai20;
using static BaiTapCoban.Bai21;
using static BaiTapCoban.Bai22;
using static BaiTapCoban.Bai23;
using static BaiTapCoban.Bai24;
using static BaiTapCoban.Bai25;
using static BaiTapCoban.Bai26;
using static BaiTapCoban.Bai27;
using static BaiTapCoban.Bai28;
using static BaiTapCoban.Bai29;
using static BaiTapCoban.Bai30;



namespace BaiTapCoban
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("-------------------------------------------- Bai 1 ---------------------------------------------");
            BT1 bt1 = new BT1();
            //bt1.vHinhCau();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 2 ---------------------------------------------");
            BT2 bt2 = new BT2();
            //bt2.khoangCachAB();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 3 ---------------------------------------------");
            BT3 bt3 = new BT3();
            //bt3.xdDiemM();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 4 ---------------------------------------------");
            BT4 bt4 = new BT4();
            //bt4.tamgiac();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 5 ---------------------------------------------");
            BT5 bt5 = new BT5();
            //bt5.toaDoTamGiac();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 6 ---------------------------------------------");
            BT6 bt6 = new BT6();
            //bt6.sapXep();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 7 ---------------------------------------------");
            BT7 bt7 = new BT7();
            //bt7.pt1();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 8 ---------------------------------------------");
            BT8 bt8 = new BT8();
            //bt8.pt2();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 9 ---------------------------------------------");
            BT9 bt9 = new BT9();
            //bt9.vTron();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 10 --------------------------------------------");
            BT10 bt10 = new BT10();
            bt10.SIN();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 11 ---------------------------------------------");
            BT11 bt11= new BT11();
            bt11.KBB();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 12 ---------------------------------------------");
            BT12 bt12 = new BT12();
            bt12.pt2an();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 13 ---------------------------------------------");
            BT13 bt13 = new BT13();
            bt13.ngayThang();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 14 ---------------------------------------------");
            BT14 bt14 = new BT14();
            bt14.ngayKeTiep();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 15 ---------------------------------------------");
            BT15 bt15 = new BT15();
            bt15.ngayTrongNam();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 16 ---------------------------------------------");
            BT16 bt16 = new BT16();
            bt16.inlich();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 17 ---------------------------------------------");
            BT17 bt17 = new BT17();
            bt17.taoLichTruc();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 18 ---------------------------------------------");
            BT18 bt18 = new BT18();
            bt18.soGio();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 19 ---------------------------------------------");
            BT19 bt19 = new BT19();
            bt19.khoangTG();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 20 ---------------------------------------------");
            BT20 bt20 = new BT20();
            bt20.tienDien();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 21 ---------------------------------------------");
            BT21 bt21 = new BT21();
            bt21.ketqua();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 22 ---------------------------------------------");
            BT22 bt22 = new BT22();
            bt22.uocSo();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 23 ---------------------------------------------");
            BT23 bt23 = new BT23();
            bt23.soHoanhao();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 24 ---------------------------------------------");
            BT24 bt24 = new BT24();
            bt24.soNgauNhien();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 25 ---------------------------------------------");
            BT25 bt25 = new BT25();
            bt25.uocSoBoiSo();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 26 ---------------------------------------------");
            BT26 bt26 = new BT26();
            bt26.toiGian();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 27 ---------------------------------------------");
            BT27 bt27 = new BT27();
            bt27.phanTich();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 28 ---------------------------------------------");
            BT28 bt28 = new BT28();
            bt28.hamRound();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 29 ---------------------------------------------");
            BT29 bt29 = new BT29();
            bt29.nhietDo();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("-------------------------------------------- Bai 30 ---------------------------------------------");
            BT30 bt30 = new BT30();
            bt30.laiXuat();
            Console.WriteLine("");
            Console.WriteLine("");
            Console.WriteLine("");






            Console.ReadKey();
        }
    }
}
